/* ============================================================
   reader.js — the audiobook engine

   Honest summary of what this can and cannot do:

   It uses the browser's built-in speech synthesis. That is free,
   needs no server, and works offline once the voice is on the
   device. What it cannot do is survive an iPhone screen lock —
   iOS suspends speech synthesis when Safari is backgrounded, and
   no amount of JavaScript changes that. On Android Chrome it
   usually keeps going with the screen off; on desktop it always
   does. The app says so plainly rather than pretending.

   To make it survive properly on iOS you would need real audio
   files generated by a text-to-speech service and played through
   an <audio> element. That is a paid service plus a build step,
   which is why it is not the default here.
   ============================================================ */

const synth = window.speechSynthesis;

const state = {
  article: null,        // { id, title, chunks: [] }
  index: 0,
  playing: false,
  rate: 1,
  voiceURI: '',
  onUpdate: () => {},
};

let silent = null;      // keeps the media session alive on Android

/* ---------------------------------------------------------- */
/*  support                                                    */
/* ---------------------------------------------------------- */

export const supported = () => typeof window !== 'undefined' && 'speechSynthesis' in window;

export function voices() {
  if (!supported()) return [];
  return synth.getVoices().filter(v => /^en/i.test(v.lang));
}

/* Voices load asynchronously in most browsers. */
export function onVoices(cb) {
  if (!supported()) return;
  if (synth.getVoices().length) cb(voices());
  synth.addEventListener('voiceschanged', () => cb(voices()));
}

/* iOS suspends speech when the tab is backgrounded. Detect it so
   the UI can tell the truth instead of guessing. */
export const isIOS = () =>
  /iPad|iPhone|iPod/.test(navigator.userAgent) ||
  (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1);

/* ---------------------------------------------------------- */
/*  turning an article into speakable chunks                   */
/* ---------------------------------------------------------- */

/** Markdown in, list of speakable strings out. Headings are kept
    as their own chunk so you can hear the structure. */
export function toChunks(markdown) {
  const out = [];
  const lines = String(markdown || '').split('\n');

  for (let raw of lines) {
    let line = raw.trim();
    if (!line) continue;

    // skip table rules
    if (/^\|[\s:|-]+\|$/.test(line)) continue;

    // headings — spoken with a pause marker
    const hm = line.match(/^(#{1,6})\s+(.*)/);
    if (hm) { out.push({ text: clean(hm[2]), heading: true }); continue; }

    // table rows read as "cell, cell, cell"
    if (/^\|/.test(line)) {
      const cells = line.split('|').slice(1, -1).map(c => clean(c.trim())).filter(Boolean);
      if (cells.length) out.push({ text: cells.join(', ') + '.' });
      continue;
    }

    line = line.replace(/^\s*[-*•]\s+/, '').replace(/^\s*\d+[.)]\s+/, '').replace(/^>\s?/, '');
    const text = clean(line);
    if (!text) continue;

    // split long paragraphs into sentences so seeking is useful
    // and so a pause never lands in the middle of a thought
    const sentences = text.match(/[^.!?]+[.!?]+["')\]]*|\S[^.!?]*$/g) || [text];
    let buf = '';
    sentences.forEach(s => {
      const t = s.trim();
      if (!t) return;
      if ((buf + ' ' + t).trim().length > 240) { if (buf) out.push({ text: buf.trim() }); buf = t; }
      else buf = (buf + ' ' + t).trim();
    });
    if (buf) out.push({ text: buf });
  }
  return out;
}

/* Strip markdown emphasis and links, and expand things a speech
   engine reads badly. */
function clean(s) {
  return String(s)
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/[*_`]/g, '')
    .replace(/\bT-(\d+)\b/g, 'T minus $1')
    .replace(/\bT\+(\d+)\b/g, 'T plus $1')
    .replace(/&/g, ' and ')
    .replace(/\s+/g, ' ')
    .trim();
}

/* ---------------------------------------------------------- */
/*  playback                                                   */
/* ---------------------------------------------------------- */

export function load(article, chunks, startAt = 0) {
  stop();
  state.article = article;
  state.chunks = chunks;
  state.index = Math.min(Math.max(0, startAt), Math.max(0, chunks.length - 1));
  state.onUpdate(snapshot());
}

export function play() {
  if (!supported() || !state.chunks?.length) return;
  synth.cancel();
  state.playing = true;
  startSilent();
  speakCurrent();
  state.onUpdate(snapshot());
}

function speakCurrent() {
  const chunk = state.chunks[state.index];
  if (!chunk) { finish(); return; }

  const u = new SpeechSynthesisUtterance(chunk.text);
  u.rate = state.rate;
  u.pitch = 1;
  const v = voices().find(x => x.voiceURI === state.voiceURI);
  if (v) u.voice = v;

  u.onend = () => {
    if (!state.playing) return;
    state.index++;
    if (state.index >= state.chunks.length) { finish(); return; }
    state.onUpdate(snapshot());
    speakCurrent();
  };
  u.onerror = (e) => {
    // 'interrupted' and 'canceled' are what a normal stop looks like
    if (e.error === 'interrupted' || e.error === 'canceled') return;
    state.playing = false;
    state.onUpdate(snapshot());
  };

  try { synth.speak(u); } catch { state.playing = false; state.onUpdate(snapshot()); }
  updateMediaSession();
}

export function pause() {
  state.playing = false;
  try { synth.cancel(); } catch {}
  stopSilent();
  state.onUpdate(snapshot());
}

export function toggle() { state.playing ? pause() : play(); }

export function stop() {
  state.playing = false;
  try { synth.cancel(); } catch {}
  stopSilent();
  state.article = null;
  state.chunks = [];
  state.index = 0;
  state.onUpdate(snapshot());
}

function finish() {
  state.playing = false;
  stopSilent();
  state.index = Math.max(0, state.chunks.length - 1);
  state.onUpdate(snapshot(), { ended: true });
}

export function seek(i) {
  if (!state.chunks?.length) return;
  state.index = Math.min(Math.max(0, i), state.chunks.length - 1);
  if (state.playing) { synth.cancel(); speakCurrent(); }
  state.onUpdate(snapshot());
}
export const next = () => seek(state.index + 1);
export const prev = () => seek(state.index - 1);

export function setRate(r) {
  state.rate = Math.min(2.5, Math.max(0.5, +r || 1));
  if (state.playing) { synth.cancel(); speakCurrent(); }
  state.onUpdate(snapshot());
}
export function setVoice(uri) {
  state.voiceURI = uri;
  if (state.playing) { synth.cancel(); speakCurrent(); }
  state.onUpdate(snapshot());
}

export const onUpdate = (fn) => { state.onUpdate = fn; };

export function snapshot() {
  return {
    article: state.article,
    index: state.index,
    total: state.chunks?.length || 0,
    playing: state.playing,
    rate: state.rate,
    voiceURI: state.voiceURI,
    text: state.chunks?.[state.index]?.text || '',
    pct: state.chunks?.length ? (state.index + 1) / state.chunks.length * 100 : 0,
  };
}

/* ---------------------------------------------------------- */
/*  background survival                                        */
/* ---------------------------------------------------------- */

/* A looping silent track keeps the page's audio session alive,
   which on Android is what stops Chrome throttling the tab and
   gives us lock-screen controls. It does nothing on iOS, where
   speech synthesis is suspended regardless. */
function startSilent() {
  try {
    if (!silent) {
      silent = new Audio(SILENCE);
      silent.loop = true;
      silent.volume = 0.001;
    }
    silent.play().catch(() => {});
  } catch {}
}
function stopSilent() { try { silent?.pause(); } catch {} }

function updateMediaSession() {
  if (!('mediaSession' in navigator) || !state.article) return;
  try {
    navigator.mediaSession.metadata = new MediaMetadata({
      title: state.article.title,
      artist: state.article.subtitle || 'Sid — history',
      album: 'Sid',
      artwork: [{ src: './icons/icon-512.png', sizes: '512x512', type: 'image/png' }],
    });
    navigator.mediaSession.playbackState = state.playing ? 'playing' : 'paused';
    navigator.mediaSession.setActionHandler('play', () => play());
    navigator.mediaSession.setActionHandler('pause', () => pause());
    navigator.mediaSession.setActionHandler('previoustrack', () => prev());
    navigator.mediaSession.setActionHandler('nexttrack', () => next());
  } catch {}
}

/* 1-second silent wav, base64 */
const SILENCE = 'data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAgD4AAAB9AAACABAAZGF0YQAAAAA=';

/* Chrome stops speaking after ~15 seconds unless nudged. This is a
   long-standing bug and the resume ping is the standard workaround. */
if (supported()) {
  setInterval(() => {
    if (state.playing && !synth.speaking) return;
    if (state.playing && synth.speaking) { synth.pause(); synth.resume(); }
  }, 10000);
}
